name: Check operator test status

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    # 6am on fridays
    - cron: '0 6 * * 5'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions: write-all
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    
    env:
      TERCEN_COMMITTER_NAME: ${{ secrets.TERCEN_COMMITTER_NAME_AG }}
      TERCEN_COMMITTER_EMAIL: ${{ secrets.TERCEN_COMMITTER_EMAIL_AG }}
      GITHUB_TOKEN: ${{ secrets.TERCEN_GITHUB_PAT }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
        
    - name: Install R packages
      run: |
        install.packages('dplyr')
        install.packages('jsonlite')
        install.packages('gh')
        install.packages('digest')
      shell: Rscript {0}
      
    - name: Check test status
      run: |
        source("./check_test_status.R")
      shell: Rscript {0}
